=== gadgetron/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two sections: port and globalGadgetParameters
    The 'port' is where gadgetron is listening to. The 'globalGadgetParameters' section 
    lists the parameters which will be pre-set for all gadgets
    e.g. if 'workingDirectory' in the globalGadgetParameters is set, the dependency measurements
    will be stored and read from this directory. If it is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->
    <xs:complexType name="Readers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Writers">
        <xs:sequence>
            <xs:element name="reader" type="Reader"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="configuration">
        <xs:complexType>
            <xs:all>
            <xs:element name="version" type="xs:string"/>
                <xs:element name="readers" type="Readers"/>
                <xs:element name="writers" type="Writers"/>
                <xs:element name="stream" type="Stream" />

            </xs:all>
        </xs:complexType>

    </xs:element>



  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gadgetron/gadgetron/gadgets/mri_core/generic_recon_gadgets/config/Generic_Cartesian_OpenRecon_Demo.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- reader -->
    <reader><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageReader</classname></reader>
    <reader><slot>1026</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdWaveformMessageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>

    <!-- Noise prewhitening -->
    <gadget><name>NoiseAdjust</name><dll>gadgetron_mricore</dll><classname>NoiseAdjustGadget</classname></gadget>

    <!-- RO asymmetric echo handling -->
    <gadget><name>AsymmetricEcho</name><dll>gadgetron_mricore</dll><classname>AsymmetricEchoAdjustROGadget</classname></gadget>

    <!-- RO oversampling removal -->
    <gadget><name>RemoveROOversampling</name><dll>gadgetron_mricore</dll><classname>RemoveROOversamplingGadget</classname></gadget>

    <!-- Data accumulation and trigger gadget -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property><name>trigger_dimension</name><value></value></property>
        <property><name>sorting_dimension</name><value></value></property>
    </gadget>

    <gadget>
        <name>BucketToBuffer</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property><name>N_dimension</name><value>repetition</value></property>
        <property><name>S_dimension</name><value>set</value></property>
        <property><name>split_slices</name><value>false</value></property>
        <property><name>ignore_segment</name><value>true</value></property>
        <property><name>verbose</name><value>false</value></property>
    </gadget>

    <!-- Prep ref -->
    <gadget>
        <name>PrepRef</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconCartesianReferencePrepGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>false</value></property>

        <!-- averaging across repetition -->
        <property><name>average_all_ref_N</name><value>true</value></property>
        <!-- every set has its own kernels -->
        <property><name>average_all_ref_S</name><value>true</value></property>
        <!-- whether always to prepare ref if no acceleration is used -->
        <property><name>prepare_ref_always</name><value>true</value></property>
    </gadget>

    <!-- Recon -->
    <gadget>
        <name>Recon</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconOpenReconDemoGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>
    </gadget>

    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <!-- after recon processing -->
    <gadget>
        <name>ComplexToFloatAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>ComplexToFloatGadget</classname>
    </gadget>

    <gadget>
        <name>FloatToShortAttrib</name>
        <dll>gadgetron_mricore</dll>
        <classname>FloatToUShortGadget</classname>

        <property><name>max_intensity</name><value>32767</value></property>
        <property><name>min_intensity</name><value>-32767</value></property>
        <property><name>intensity_offset</name><value>0</value></property>
    </gadget>

    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/examples/config/stream_image_array_scaling.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- Image Array Scaling -->
    <gadget>
        <name>Scaling</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconImageArrayScalingGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>perform_timing</name><value>false</value></property>
        <property><name>verbose</name><value>false</value></property>

        <property><name>min_intensity_value</name><value>64</value></property>
        <property><name>max_intensity_value</name><value>4095</value></property>
        <property><name>scalingFactor</name><value>10.0</value></property>
        <property><name>use_constant_scalingFactor</name><value>true</value></property>
        <property><name>auto_scaling_only_once</name><value>true</value></property>
        <property><name>scalingFactor_dedicated</name><value>100.0</value></property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/mri_core/default_measurement_dependencies.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
                  xmlns="http://gadgetron.sf.net/gadgetron"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>

    <!-- SNR unit noise adjust gadget 
         If the scan has asymmetric readout, the center of echo will shifted to the index 0
         Zeros will be filled into the readout data
    -->
    <gadget>
        <name>NoiseAdjust</name>
        <dll>gadgetron_mricore</dll>
        <classname>NoiseAdjustGadget</classname>

        <!-- File prefix for stored noise prewhitener matrix -->
        <property>
            <name>noise_dependency_prefix</name>
            <value>GadgetronNoiseCovarianceMatrix</value>
        </property>

        <!-- Whether to perform timing -->
        <property>
            <name>performTiming</name>
            <value>true</value>
        </property>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/moco/config/cpureg_cartesian_averaging.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <reader>
    <slot>1008</slot>
    <dll>gadgetron_mricore</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>
    <reader>
        <slot>1026</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdWaveformMessageReader</classname>
    </reader>

  <writer>
    <slot>1022</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriter</classname>
  </writer>

  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_mricore</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>

  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>
  
  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>16</value></property>
  </gadget>

  <gadget>
    <name>CartesianToGenericGadget</name>
    <dll>gadgetron_cartesian</dll>
    <classname>CartesianToGenericGadget</classname>
    <!-- Property 'matrix_size_as_a_multiple_of' is required for the gpu nfft 
	 to enforce the matrix size to be a multiple of the gpu warp size (32) -->
    <property><name>matrix_size_as_a_multiple_of</name><value>32</value></property>
  </gadget>

  <gadget>
    <name>gpuGenericSensePrepGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuGenericSensePrepGadget</classname>
    <property><name>deviceno</name><value>0</value></property>
    <property><name>rotations_per_reconstruction</name><value>8</value></property>
    <property><name>buffer_convolution_kernel_width</name><value>5.5</value></property>
    <property><name>buffer_convolution_oversampling_factor</name><value>1.25</value></property>
  </gadget>
  
  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>0</value></property>
    <property><name>number_of_iterations</name>    <value>20</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>5.5</value></property>
    <property><name>kappa</name>                   <value>0.05</value></property>
    <property><name>output_convergence</name><value>true</value></property>
  </gadget>

  <gadget>
    <name>PhysioInterpolationGadget</name>
    <dll>gadgetron_mricore</dll>
    <classname>PhysioInterpolationGadget</classname>
    <property><name>mode</name><value>0</value></property>
    <property><name>phase</name><value>30</value></property>
  </gadget>

  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>

  <gadget>
    <name>cpuRegistrationAveragingGadget2D</name>
    <dll>gadgetron_moco</dll>
    <classname>cpuRegistrationAveragingGadget2D</classname>
    <property><name>alpha</name><value>0.05</value></property>
    <property><name>beta</name><value>1.0</value></property>
    <property><name>num_multiresolution_levels</name><value>3</value></property>
    <property><name>output_convergence</name><value>true</value></property>
    <property><name>phase</name><value>phase@PhysioInterpolationGadget</value></property>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageFinishFloat</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
      </gadget>    
  -->

  <gadget>
    <name>AutoScale</name>
    <dll>gadgetron_mricore</dll>
    <classname>AutoScaleGadget</classname>
  </gadget>

  <gadget>
    <name>FloatToShort</name>
    <dll>gadgetron_mricore</dll>
    <classname>FloatToUShortGadget</classname>
  </gadget>

  <gadget>
    <name>ImageFinish</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadget</classname>
  </gadget>
  
</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/bart/BART_Recon_cloud.xml
<?xml version="2.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!--
        Gadgetron generic recon chain for 2D and 3D cartesian sampling

        RealTimeCine imaging
        Triggered by slice
        Recon N is phase and S is set

        Author: Hui Xue
        Magnetic Resonance Technology Program, National Heart, Lung and Blood Institute, National Institutes of Health
        10 Center Drive, Bethesda, MD 20814, USA
        Email: hui.xue@nih.gov
    -->

    <!-- reader -->
    <reader><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageReader</classname></reader>
    <reader><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageReader</classname></reader>

    <!-- writer -->
    <writer><slot>1022</slot><dll>gadgetron_mricore</dll><classname>MRIImageWriter</classname></writer>
    <writer><slot>1008</slot><dll>gadgetron_mricore</dll><classname>GadgetIsmrmrdAcquisitionMessageWriter</classname></writer>

    <!-- Noise prewhitening -->
    <gadget><name>NoiseAdjust</name><dll>gadgetron_mricore</dll><classname>NoiseAdjustGadget</classname></gadget>

    <!-- RO asymmetric echo handling -->
    <gadget><name>AsymmetricEcho</name><dll>gadgetron_mricore</dll><classname>AsymmetricEchoAdjustROGadget</classname></gadget>

    <!-- RO oversampling removal -->
    <gadget><name>RemoveROOversampling</name><dll>gadgetron_mricore</dll><classname>RemoveROOversamplingGadget</classname></gadget>

    <!-- Distribute slice over nodes -->
    <gadget>
      <name>Distribute</name>
      <dll>gadgetron_distributed</dll>
      <classname>IsmrmrdAcquisitionDistributeGadget</classname>
      <property><name>parallel_dimension</name><value>slice</value></property>
      <property><name>use_this_node_for_compute</name><value>false</value></property>
    </gadget>

    <!-- Data accumulation and trigger gadget -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
        <classname>AcquisitionAccumulateTriggerGadget</classname>
        <property><name>trigger_dimension</name><value>slice</value></property>
        <property><name>sorting_dimension</name><value></value></property>
    </gadget>

    <gadget>
        <name>BucketToBuffer</name>
        <dll>gadgetron_mricore</dll>
        <classname>BucketToBufferGadget</classname>
        <property><name>N_dimension</name><value>phase</value></property>
        <property><name>S_dimension</name><value>set</value></property>
        <property><name>split_slices</name><value>true</value></property>
        <property><name>ignore_segment</name><value>true</value></property>
    </gadget>

	<!-- Prep ref -->
    <gadget>
        <name>PrepRef</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconCartesianReferencePrepGadget</classname>

        <!-- parameters for debug and timing -->
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>true</value></property>
        <property><name>verbose</name><value>true</value></property>

        <!-- averaging across repetition -->
        <property><name>average_all_ref_N</name><value>true</value></property>
        <!-- every set has its own kernels -->
        <property><name>average_all_ref_S</name><value>false</value></property>
        <!-- whether always to prepare ref if no acceleration is used -->
        <property><name>prepare_ref_always</name><value>true</value></property>
    </gadget>

	<!-- This is where we insert our new Gadget -->
	<gadget>
	  <name>bartgadget</name>
	  <dll>gadgetron_bart</dll>
	  <classname>BartGadget</classname>
	  <!-- The "AbsoluteBartCommandScript_path" can be provided by the user to overwrite the default value-->
	  <!--
	  <property><name>AbsoluteBartCommandScript_path</name><value></value></property>
	  -->
	  <property><name>BartWorkingDirectory</name><value>/tmp/</value></property>
	  <property><name>BartCommandScript_name</name><value>Sample_Grappa_Recon.sh</value></property>
	  <property><name>isBartFileBeingStored</name><value>false</value></property>
          <property><name>image_series</name><value>0</value></property>
	  
         <property><name>isBartFolderBeingCachedToVM</name><value>false</value></property>
	  <property><name>AllocateMemorySizeInMegabytes</name><value>50</value></property>
	</gadget>

    <!-- Partial fourier handling -->
    <gadget>
         <name>PartialFourierHandling</name>
         <dll>gadgetron_mricore</dll>
         <classname>GenericReconPartialFourierHandlingPOCSGadget</classname>
         <property><name>debug_folder</name><value></value></property>
         <property><name>perform_timing</name><value>false</value></property>
         <property><name>verbose</name><value>true</value></property>
         <property><name>skip_processing_meta_field</name><value>Skip_processing_after_recon</value></property>
         <property><name>partial_fourier_POCS_iters</name><value>6</value></property>
         <property><name>partial_fourier_POCS_thres</name><value>0.01</value></property>
         <property><name>partial_fourier_POCS_transitBand</name><value>24</value></property>
         <property><name>partial_fourier_POCS_transitBand_E2</name><value>16</value></property>
    </gadget>

 <!-- Kspace filtering -->
  <gadget>
        <name>KSpaceFilter</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconKSpaceFilteringGadget</classname>
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>false</value></property>
        <property><name>verbose</name><value>false</value></property>
        <property><name>skip_processing_meta_field</name><value>Skip_processing_after_recon</value></property>
        <property><name>filterRO</name><value>Gaussian</value></property>
        <property><name>filterRO_sigma</name><value>1.0</value></property>
        <property><name>filterRO_width</name><value>0.15</value></property>
        <property><name>filterE1</name><value>Gaussian</value></property>
        <property><name>filterE1_sigma</name><value>1.0</value></property>
        <property><name>filterE1_width</name><value>0.15</value></property>
        <property><name>filterE2</name><value>Gaussian</value></property>
        <property><name>filterE2_sigma</name><value>1.0</value></property>
        <property><name>filterE2_width</name><value>0.15</value></property>
   </gadget>
                                                                                                                            |
   <!-- FOV Adjustment -->
    <gadget>
        <name>FOVAdjustment</name>
        <dll>gadgetron_mricore</dll>
        <classname>GenericReconFieldOfViewAdjustmentGadget</classname>
        <property><name>debug_folder</name><value></value></property>
        <property><name>perform_timing</name><value>false</value></property>
        <property><name>verbose</name><value>false</value></property>
    </gadget>

    <!-- ImageArray to images -->
    <gadget>
        <name>ImageArraySplit</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageArraySplitGadget</classname>
    </gadget>

    <!-- Collect images from nodes -->
    <gadget>
        <name>Collect</name>
        <dll>gadgetron_distributed</dll>
        <classname>CollectGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>
    
    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
	
    <gadget>
        <name>ImageFinish</name>
        <dll>gadgetron_mricore</dll>
        <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== gadgetron/gadgetron/gadgets/python/legacy/config/python_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
    <reader>
        <slot>1026</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdWaveformMessageReader</classname>
    </reader>

    <writer>
      <slot>1022</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriter</classname>
    </writer>

    <gadget>
      <name>RemoveOversamplingPython</name>
      <dll>gadgetron_python</dll>
      <classname>PythonGadget</classname>
      <property><name>python_path</name>                  <value>/home/myuser/scripts/python</value></property>
      <property><name>python_module</name>                <value>remove_2x_oversampling</value></property>
      <property><name>python_class</name>                <value>Remove2xOversampling</value></property>
    </gadget>

    <gadget>
      <name>AccReconPython</name>
      <dll>gadgetron_python</dll>
      <classname>PythonGadget</classname>
      <property><name>python_path</name>                  <value>/home/myuser/scripts/python</value></property>
      <property><name>python_module</name>                <value>accumulate_and_recon</value></property>
      <property><name>python_class</name>                <value>AccumulateAndRecon</value></property>
    </gadget>

    <gadget>
      <name>CoilCombinePython</name>
      <dll>gadgetron_python</dll>
      <classname>PythonGadget</classname>
      <property><name>python_path</name>                  <value>/home/myuser/scripts/python</value></property>
      <property><name>python_module</name>                <value>rms_coil_combine</value></property>
      <property><name>python_class</name>                <value>RMSCoilCombine</value></property>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
     </gadget>

     <gadget>
      <name>Autoscale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
     </gadget>
    
     <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
  
    <gadget>
      <name>ImageFinish</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadget</classname>
    </gadget>

</gadgetronStreamConfiguration>
